[[profile]]
name = "laptop builtin"
  [[profile.output]]
  match = "eDP-1"
  enable = true

[[profile]]
name = "HomeOffice"
  [[profile.output]]
  search = "eDP-1"
  enable = false

  [[profile.output]]
#search = "/.*S2721DS D3K2R43.*/"
  search = "HDMI-A-1"
  mode = "best"
  enable = true
  transform = "90"
  position = { x=0, y=0}
  adaptive_sync = false
  [[profile.output]]
#search = "/.*M32QC 21390B000953.*/"
  search = "DP-1"
  mode = "best"
  transform = "normal"
  enable = true
  position = { x=1440, y=500}
  adaptive_sync = true
